# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: ðŸ”® Ephemeral deployment
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout@v4

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - run: make build
        env:
          PUBLIC_POCKETBASE_URL: "https://staging.admin.didroom.com/"
      - name: Configure ðŸ”’ðŸš
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_SKEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            IdentitiesOnly yes
            StrictHostKeyChecking no
            Port $SSH_PORT
          END
        env:
          SSH_USER: ${{ secrets.GA_DEPLOY_USER }}
          SSH_SKEY: ${{ secrets.GA_DEPLOY_SK }}
          SSH_HOST: ${{ secrets.GA_DEPLOY_HOST }}
          SSH_PORT: ${{ secrets.GA_DEPLOY_PORT }}
      - run: ssh remote 'mkdir -p ephemeral/${{ github.event.number }}'
      - run: |
          tar czf bolus.tar.gz \
            .bin/zenroom \
            .bin/zencode-exec \
            webapp/build \
            webapp/package.json \
            webapp/node_modules
          scp bolus.tar.gz remote:ephemeral/${{ github.event.number }}
      - run: |
          ssh remote 'ephemeral_deploy.sh ${{ github.event.number }}'


