# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: ðŸ”® Ephemeral deployment
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: dyne/pnpm@main
        with:
          submodules: true
          build: pnpm build
          pnpm-version: 9.1.4
          node-version: 20.14.0
          working-directory: webapp
        env:
          PB_ADMIN_USER: ${{ secrets.PB_USER }}
          PB_ADMIN_PASS: ${{ secrets.PB_PASS }}
          PB_TYPEGEN_EMAIL: ${{ secrets.PB_USER }}
          PB_TYPEGEN_PASSWORD: ${{ secrets.PB_PASS }}
          PB_TYPEGEN_URL: "https://staging.admin.didroom.com"
          PUBLIC_POCKETBASE_URL: "https://staging.admin.didroom.com/"

      - name: Configure ðŸ”’ðŸš
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_SKEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            IdentitiesOnly yes
            StrictHostKeyChecking no
            Port $SSH_PORT
          END
        env:
          SSH_USER: ${{ secrets.GA_DEPLOY_USER }}
          SSH_HOST: ${{ secrets.GA_DEPLOY_HOST }}
          SSH_PORT: ${{ secrets.GA_DEPLOY_PORT }}
          SSH_SKEY: ${{ secrets.GA_DEPLOY_SK }}
      - run: ssh remote 'mkdir -p ephemeral/${{ github.event.number }}'
      - run: |
          tar czf bolus.tar.gz \
            webapp/build \
            webapp/package.json \
            webapp/node_modules
          scp bolus.tar.gz remote:ephemeral/${{ github.event.number }}
      - run: |
          ssh remote './ephemeral_deploy.sh ${{ github.event.number }}'
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Release ${{ github.sha }} to <https://${{ github.event.number }}.pr.didroom.com>


